const characters = [
    {
        name: "hand",
        url: "/models/Characters/handFull.glb",
        model: null,
        mixer: null,
        actions: null,
        scale: 0.01,
    },
    {
        name: "ball",
        url: "/models/Characters/ball.glb",
        model: null,
        mixer: null,
        actions: null,
        scale: 0.01,
    },
    {
        name: "dog",
        url: "/models/Characters/dog.glb",
        model: null,
        mixer: null,
        actions: null,
        scale: 0.01,
    },
    {
        name: "birdHand",
        url: "/models/Characters/bird-hand.glb",
        model: null,
        mixer: null,
        actions: null,
        scale: 0.01,
    },
    {
        name: "boidBird",
        url: "/models/Characters/boid-bird.glb",
        model: null,
        mixer: null,
        actions: null,
        scale: 0.03,
    },
    {
        name: "sheep_hater",
        url: "/models/Characters/sheep_hater.glb",
        model: null,
        mixer: null,
        actions: null,
        scale: 0.01,
    },
    {
        name: "sheep_door",
        url: "/models/Characters/sheep_door.glb",
        model: null,
        mixer: null,
        actions: null,
        scale: 0.01,
    },
    {
        name: "sheep_hill",
        url: "/models/Characters/sheep_hill.glb",
        model: null,
        mixer: null,
        actions: null,
        scale: 0.01,
    },
    {
        name: "sheep_rock",
        url: "/models/Characters/sheep_rock.glb",
        model: null,
        mixer: null,
        actions: null,
        scale: 0.01,
    },
    {
        name: "sheep_house",
        url: "/models/Characters/sheep_house.glb",
        model: null,
        mixer: null,
        actions: null,
        scale: 0.01,
    },

]


export default characters